<a href="https://colab.research.google.com/github/ibrahimabdulj/Plant-Disease-Detection-System/blob/main/plantdesiesdetection1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import os

#Instead of downloading the dataset locally and open it on my system i'll download and provide the path from kaggle
  

In [2]:
import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print("Path to dataset files:", path)
print("Contents of the dataset root directory:", os.listdir(path))
print("Contents of 'new plant diseases dataset(augmented)':", os.listdir(os.path.join(path, 'new plant diseases dataset(augmented)')))

Using Colab cache for faster access to the 'new-plant-diseases-dataset' dataset.
Path to dataset files: /kaggle/input/new-plant-diseases-dataset
Contents of the dataset root directory: ['New Plant Diseases Dataset(Augmented)', 'new plant diseases dataset(augmented)', 'test']
Contents of 'new plant diseases dataset(augmented)': ['New Plant Diseases Dataset(Augmented)']


##Data Preprocessing


###Training preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path, 'new plant diseases dataset(augmented)', 'New Plant Diseases Dataset(Augmented)', 'train'),
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


###Validation Image Preprocessing

In [4]:
Validation_set = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path, 'new plant diseases dataset(augmented)', 'New Plant Diseases Dataset(Augmented)', 'valid'),
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [5]:
training_set


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [6]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[ 85.75  80.25  83.75]
   [ 76.5   71.5   74.5 ]
   [ 83.5   77.5   81.5 ]
   ...
   [ 83.75  75.25  74.75]
   [ 82.    72.75  72.25]
   [ 80.25  71.    70.25]]

  [[144.5  138.5  142.5 ]
   [158.5  152.5  156.5 ]
   [165.25 159.25 163.25]
   ...
   [166.75 156.75 155.75]
   [157.   147.   146.  ]
   [154.5  144.5  143.5 ]]

  [[147.   141.   145.  ]
   [160.75 154.75 158.75]
   [162.   156.   160.  ]
   ...
   [165.75 155.75 154.75]
   [155.5  145.5  144.5 ]
   [160.5  150.5  149.5 ]]

  ...

  [[184.   179.   185.  ]
   [185.75 180.75 186.75]
   [173.75 168.75 174.75]
   ...
   [181.   175.   179.  ]
   [179.5  173.5  177.5 ]
   [180.   174.   178.  ]]

  [[184.25 179.25 185.25]
   [166.25 161.25 167.25]
   [176.5  171.5  177.5 ]
   ...
   [185.   179.   183.  ]
   [180.5  174.5  178.5 ]
   [174.   168.   172.  ]]

  [[182.25 177.25 183.25]
   [183.   178.   184.  ]
   [177.25 172.25 178.25]
   ...
   [183.   177.   181.  ]
   [180.5  174.5  178.5 ]
   [182.25 176.25 18

##To avoid Overshooting
1. Choose small learning rate default 0.001 changed to 0.0001
2. They maybe be chnace of Underfitting, so increase number of Neurons
3. Add more Convolution layers to extract more features from thr images its possibly that model unable to capture relevants features or model is confusing due to lack features so feed with more features

##Building Model Architecture

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout

In [8]:
model = Sequential()


Building Convolution layer using MAxPooling Operation

In [9]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [11]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [12]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [13]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Dropout(0.25)) # To avoid Overfitting

Flattening Operation

In [15]:
model.add(Flatten())
model.add(Dense(units=1500,activation='relu'))


###OutPut Layer

In [16]:
model.add(Dense(units=38,activation='softmax'))

In [17]:
##model.add(Dropout(0.4))

Compilling Model


In [18]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.003),loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

##Model Training

In [20]:
training_history = model.fit(x=training_set,epochs=10,validation_data=Validation_set)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 360s 157ms/step - accuracy: 0.1343 - loss: 4.6217 - val_accuracy: 0.4231 - val_loss: 1.8980
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 134s 61ms/step - accuracy: 0.4474 - loss: 1.8360 - val_accuracy: 0.4236 - val_loss: 1.8590
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 134s 61ms/step - accuracy: 0.4942 - loss: 1.6667 - val_accuracy: 0.5534 - val_loss: 1.4290
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 133s 60ms/step - accuracy: 0.5287 - loss: 1.5401 - val_accuracy: 0.5689 - val_loss: 1.3864
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 133s 60ms/step - accuracy: 0.5533 - loss: 1.4571 - val_accuracy: 0.5812 - val_loss: 1.3501
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 133s 61ms/step - accuracy: 0.5621 - loss: 1.4051 - val_accuracy: 0.6263 - val_loss: 1.1920
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 133s 61ms/step - accuracy: 0.5557 - loss: 1.5151 - val_accuracy: 0.6317 - val_loss: 1.1799
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 133s 61ms/step - accuracy:

##Model Evaluation
###Model Evaluation on Training Set

In [22]:
train_loss,train_accuracy = model.evaluate(training_set)


2197/2197 ━━━━━━━━━━━━━━━━━━━━ 78s 36ms/step - accuracy: 0.6582 - loss: 1.0608


In [23]:
print(train_loss, train_accuracy)

1.0375728607177734 0.6665481328964233


the model achieved a training accuracy of 66.6% with a low loss of 1.0, indicating effective learning without overfitting , as performance on validation data remained comparable

In [24]:
val_loss,val_accuracy = model.evaluate(Validation_set)

550/550 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.6357 - loss: 1.1498


In [25]:
print(val_loss, val_accuracy)

1.145691156387329 0.6376621723175049


##Saving Model
###for the purpose of reuse later in the future without having to run the model all over again

In [27]:
model.save('trained_model.keras')