<a href="https://colab.research.google.com/github/ibrahimabdulj/Plant-Disease-Detection-System/blob/main/plantdesiesdetection1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import os

#Instead of downloading the dataset locally and open it on my system i'll download and provide the path from kaggle
  

In [ ]:
import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print("Path to dataset files:", path)
print("Contents of the dataset root directory:", os.listdir(path))
print("Contents of 'new plant diseases dataset(augmented)':", os.listdir(os.path.join(path, 'new plant diseases dataset(augmented)')))

Using Colab cache for faster access to the 'new-plant-diseases-dataset' dataset.
Path to dataset files: /kaggle/input/new-plant-diseases-dataset
Contents of the dataset root directory: ['New Plant Diseases Dataset(Augmented)', 'new plant diseases dataset(augmented)', 'test']
Contents of 'new plant diseases dataset(augmented)': ['New Plant Diseases Dataset(Augmented)']


##Data Preprocessing


###Training preprocessing

In [ ]:
training_set = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path, 'new plant diseases dataset(augmented)', 'New Plant Diseases Dataset(Augmented)', 'train'),
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


###Validation Image Preprocessing

In [ ]:
Validation_set = tf.keras.utils.image_dataset_from_directory(
    os.path.join(path, 'new plant diseases dataset(augmented)', 'New Plant Diseases Dataset(Augmented)', 'valid'),
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [ ]:
training_set


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [ ]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[181.5  165.5  152.5 ]
   [183.5  167.5  154.5 ]
   [184.5  168.5  155.5 ]
   ...
   [161.5  140.5  121.5 ]
   [161.5  140.5  121.5 ]
   [168.25 147.25 128.25]]

  [[182.75 166.75 153.75]
   [178.75 162.75 149.75]
   [173.75 157.75 144.75]
   ...
   [170.75 149.75 130.75]
   [160.75 139.75 120.75]
   [163.25 142.25 123.25]]

  [[173.25 157.25 144.25]
   [176.   160.   147.  ]
   [178.   162.   149.  ]
   ...
   [169.25 148.25 129.25]
   [168.5  147.5  128.5 ]
   [161.75 140.75 121.75]]

  ...

  [[187.   170.   162.  ]
   [178.5  161.5  153.5 ]
   [183.5  166.5  158.5 ]
   ...
   [151.5  132.5  117.5 ]
   [173.25 154.25 139.25]
   [145.75 126.75 111.75]]

  [[185.   168.   160.  ]
   [181.75 164.75 156.75]
   [182.   165.   157.  ]
   ...
   [168.75 149.75 134.75]
   [135.75 116.75 101.75]
   [155.5  136.5  121.5 ]]

  [[183.5  166.5  158.5 ]
   [178.25 161.25 153.25]
   [192.   175.   167.  ]
   ...
   [153.5  134.5  119.5 ]
   [149.   130.   115.  ]
   [153.   134.   11

##To avoid Overshooting
1. Choose small learning rate default 0.001 changed to 0.0001
2. They maybe be chnace of Underfitting, so increase number of Neurons
3. Add more Convolution layers to extract more features from thr images its possibly that model unable to capture relevants features or model is confusing due to lack features so feed with more features

##Building Model Architecture

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout

In [ ]:
model = Sequential()


Building Convolution layer using MAxPooling Operation

In [ ]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu',))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Dropout(0.25)) # To avoid Overfitting

Flattening Operation

In [ ]:
model.add(Flatten())
model.add(Dense(units=1500,activation='relu'))


###OutPut Layer

In [ ]:
model.add(Dense(units=38,activation='softmax'))

In [ ]:
model.add(Dropout(0.4))

Compilling Model


In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.003),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_26 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_27 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_28 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_29 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_30 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_31 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_15 (MaxPooling2D) │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_32 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_33 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_16 (MaxPooling2D) │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_34 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_35 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_17 (MaxPooling2D) │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 38)             │        57,038 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 38)             │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

##Model Training

In [ ]:
training_history = model.fit(x=training_set,epochs=10,validation_data=Validation_set)

Epoch 1/10
2099/2197 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - accuracy: 0.0272 - loss: nan

KeyboardInterrupt: 